server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 1.92.72.62
      port: 6379
      password: hexiang123321

  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    locale:
      amap-key: 13adada4d93a9974c70b5f2b5a03a38c

